//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSecond.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TilausDBEntities : DbContext
    {
        public TilausDBEntities()
            : base("name=TilausDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tuotteet> Tuotteets { get; set; }
        public virtual DbSet<Asiakkaat> Asiakkaats { get; set; }
        public virtual DbSet<Henkilot> Henkilots { get; set; }
        public virtual DbSet<Postitoimipaikat> Postitoimipaikats { get; set; }
        public virtual DbSet<Tilaukset> Tilauksets { get; set; }
        public virtual DbSet<Tilausrivit> Tilausrivits { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
